spring:
  application:
    name: feign-server

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
    register-with-eureka: true
    fetch-registry: true