spring:
  application:
    name: feign-client

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
    register-with-eureka: true
    fetch-registry: true